package gamePackage;

import java.util.ArrayList;

public class PropertyMarket {

	private ArrayList <Property> properties;
	private ArrayList <Double> rentValues;
	public PropertyMarket() {
		properties = new ArrayList<Property>();
		rentValues = new ArrayList<Double>();
		rentValues.add(2.0);
		rentValues.add(10.0);
		rentValues.add(30.0);
		rentValues.add(90.0);
		rentValues.add(160.0);
		rentValues.add(250.0);
		properties.add(new Property("Mediterranean Avenue", "brown", 60, rentValues, 1));
		rentValues = new ArrayList<Double>();
		rentValues.add(4.0);
		rentValues.add(20.0);
		rentValues.add(60.0);
		rentValues.add(180.0);
		rentValues.add(320.0);
		rentValues.add(450.0);
		properties.add(new Property("Baltic Avenue", "brown", 60, rentValues, 3));
		rentValues = new ArrayList<Double>();
		rentValues.add(25.0);
		properties.add(new Property("Reading Railroad", "Railroads", 200, rentValues, 5));
		properties.add(new Property("Pensylvania Railroad", "Railroads", 200, rentValues, 15));
		properties.add(new Property("B & O Railroad", "Railroads", 200, rentValues, 25));
		properties.add(new Property("Short Line Railroad", "Railroads", 200, rentValues, 35));
		rentValues = new ArrayList<Double>();
		rentValues.add(6.0);
		rentValues.add(30.0);
		rentValues.add(90.0);
		rentValues.add(270.0);
		rentValues.add(400.0);
		rentValues.add(550.0);
		properties.add(new Property("Oriental Avenue", "lightblue", 100, rentValues, 6));
		properties.add(new Property("Vermont Avenue", "lightblue", 100, rentValues, 8));
		rentValues = new ArrayList<Double>();
		rentValues.add(8.0);
		rentValues.add(40.0);
		rentValues.add(100.0);
		rentValues.add(300.0);
		rentValues.add(450.0);
		rentValues.add(600.0);
		properties.add(new Property("Connecticut Avenue", "lightblue", 120, rentValues, 9));
		rentValues = new ArrayList<Double>();
		rentValues.add(10.0);
		rentValues.add(50.0);
		rentValues.add(150.0);
		rentValues.add(450.0);
		rentValues.add(625.0);
		rentValues.add(750.0);
		properties.add(new Property("St. Charles Place", "purple", 140, rentValues, 11));
		properties.add(new Property("Electric Company", "utilities", 150, rentValues, 12));
		properties.add(new Property("States Avenue", "purple", 140, rentValues, 13));
		rentValues = new ArrayList<Double>();
		rentValues.add(12.0);
		rentValues.add(60.0);
		rentValues.add(180.0);
		rentValues.add(500.0);
		rentValues.add(700.0);
		rentValues.add(900.0);
		properties.add(new Property("Virginia Avenue", "purple", 160, rentValues, 14));
		rentValues = new ArrayList<Double>();
		rentValues.add(14.0);
		rentValues.add(70.0);
		rentValues.add(200.0);
		rentValues.add(550.0);
		rentValues.add(750.0);
		rentValues.add(950.0);
		properties.add(new Property("St James Place", "orange", 180, rentValues, 16));
		properties.add(new Property("Tennesse Avenue", "orange", 180, rentValues, 18));
		rentValues = new ArrayList<Double>();
		rentValues.add(16.0);
		rentValues.add(80.0);
		rentValues.add(220.0);
		rentValues.add(600.0);
		rentValues.add(800.0);
		rentValues.add(1000.0);
		properties.add(new Property("New York Avenue", "orange", 200, rentValues, 19));
		rentValues = new ArrayList<Double>();
		rentValues.add(18.0);
		rentValues.add(90.0);
		rentValues.add(250.0);
		rentValues.add(700.0);
		rentValues.add(875.0);
		rentValues.add(1050.0);
		properties.add(new Property("Kentucky Avenue", "red", 220, rentValues, 21));
		properties.add(new Property("Indiana Avenue", "red", 220, rentValues, 23));
		rentValues = new ArrayList<Double>();
		rentValues.add(20.0);
		rentValues.add(100.0);
		rentValues.add(300.0);
		rentValues.add(750.0);
		rentValues.add(925.0);
		rentValues.add(1100.0);
		properties.add(new Property("Illinois Avenue", "red", 240, rentValues, 24));
		rentValues = new ArrayList<Double>();
		rentValues.add(22.0);
		rentValues.add(110.0);
		rentValues.add(330.0);
		rentValues.add(800.0);
		rentValues.add(975.0);
		rentValues.add(1150.0);
		properties.add(new Property("Atlantic Avenue", "yellow", 260, rentValues, 26));
		properties.add(new Property("Ventnor Avenue", "yellow", 260, rentValues, 27));
		properties.add(new Property("Water Works", "utilities", 150, rentValues, 28));
		rentValues = new ArrayList<Double>();
		rentValues.add(24.0);
		rentValues.add(120.0);
		rentValues.add(360.0);
		rentValues.add(850.0);
		rentValues.add(1025.0);
		rentValues.add(1200.0);
		properties.add(new Property("Marvin Gardens", "yellow", 280, rentValues, 29));
		rentValues = new ArrayList<Double>();
		rentValues.add(26.0);
		rentValues.add(130.0);
		rentValues.add(390.0);
		rentValues.add(900.0);
		rentValues.add(1100.0);
		rentValues.add(1275.0);
		properties.add(new Property("Pacific Avenue", "green", 300, rentValues, 31));
		properties.add(new Property("North Carolina Avenue", "green", 300, rentValues, 32));
		rentValues = new ArrayList<Double>();
		rentValues.add(28.0);
		rentValues.add(150.0);
		rentValues.add(450.0);
		rentValues.add(1000.0);
		rentValues.add(1200.0);
		rentValues.add(1400.0);
		properties.add(new Property("Pennsylvania Avenue", "green", 320, rentValues, 34));
		rentValues = new ArrayList<Double>();
		rentValues.add(35.0);
		rentValues.add(175.0);
		rentValues.add(500.0);
		rentValues.add(1100.0);
		rentValues.add(1300.0);
		rentValues.add(1500.0);
		properties.add(new Property("Park Place", "blue", 350, rentValues, 37));
		rentValues = new ArrayList<Double>();
		rentValues.add(50.0);
		rentValues.add(200.0);
		rentValues.add(600.0);
		rentValues.add(1400.0);
		rentValues.add(1700.0);
		rentValues.add(2000.0);
		properties.add(new Property("Pacific Avenue", "blue", 400, rentValues, 39));
	}
	public ArrayList<Property> getProperties() {
		return properties;
	}
}
